name: pass-variable-between-jobs-action
description: 'Streamlines passing variables between jobs in a workflow'
branding:
  icon: box
  color: blue
author: 'energyenables'
inputs:
  mode:
    description: Set or get?
    required: true
  name:
    description: Variable name
    required: true
  value:
    description: Variable value
    required: false
  wait:
    description: If set, will retry getting the varaible
    required: false
  wait_retries:
    description: Number of times to retry the action
    required: false
outputs:
  value:
    description: Variable value
runs:
  using: 'node16'
  main: 'dist/index.js'
